@startuml
actor Usuario
boundary "windowLoginController" as C
control "PasswordUtils" as P
entity "UsuarioDAO" as DAO
database "MySQL" as DB

Usuario -> C : Introduce credenciales
C -> P : hashPassword(password)
P --> C : passwordHash
C -> DAO : login(username, passwordHash)
DAO -> DB : SELECT user WHERE username=? AND pass_hash=?
DB --> DAO : datos usuario/rol
DAO --> C : User (ok) / null (error)
C --> Usuario : Acceso o mensaje de error
@enduml
