INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOSEPT FP', 'Conservante');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('SOLVOTAN XS', 'Engrase');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPONAT NF', 'Calero');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOFIN CERA HF', 'Cera');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOFIN CERA HS', 'Cera');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOFIN CERA HP', 'Cera');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOSEPT BA', 'Conservante');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOFIN CERA PW', 'Cera');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOSYL TBK-E', 'Hidrofugante');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOFIN CERA PV', 'Cera');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPON AP', 'Engrase');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOCAL AF', 'Desencalante');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOSYL TBA', 'Hidrofugante');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOSOL WBF', 'Engrase');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOSYL TBD', 'Hidrofugante');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPON BMF', 'Engrase');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOCRYL K-U-10', 'Resina');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOFIN CERA DP', 'Cera');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPON CST', 'Engrase');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPON COL', 'Engrase');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOSIST S-BO', 'Hidrofugante');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOSYL TBK', 'Hidrofugante');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('PASTOSOL KC', 'Secuestrante');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('ANTIFOAM NSP', 'Engrase');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOWET SA', 'Remojo');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOFIN CERA CA', 'Cera');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOFIN CERA SP', 'Cera');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('PASTOSOL HW', 'Engrase');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOTAN MON', 'Curtición');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('PASTOSOL DG', 'Tensoactivo');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOCRYL AB', 'Resina');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOZYM AX', 'Rindente');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOCRYL A-10', 'Resina');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOFIN CERA 3A', 'Cera');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOCAL DE', 'Desencalante');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUKALIN K', 'Secuestrante');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOZYM AB', 'Rindente');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOCRYL A-18', 'Resina');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('SOLVOTAN TACTO', 'Engrase');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPONAT LA', 'Calero');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOTEC S', 'Hidrofugante');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOFIN CERA E', 'Cera');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOFIN CERA P', 'Cera');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPON DBS', 'Engrase');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOFIN CERA FP', 'Cera');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOFIN CERA M', 'Cera');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOFIN CERA K-A', 'Cera');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOFIN CERA BT', 'Cera');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOSYL ABS', 'Hidrofugante');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOCRYL A-20', 'Resina');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOFIN CERA KT 09', 'Cera');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPON DB-80', 'Engrase');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOFIN CERA KT 08', 'Cera');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPON CM', 'Engrase');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOFIN CERA W', 'Cera');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOTEC T', 'Hidrofugante');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOCRYL A-28', 'Resina');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOCRYL K-U-310', 'Resina');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOTAN MOW', 'Curtición');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOCRYL K-A-30', 'Resina');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('PASTOSOL F', 'Tensoactivo');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('PASTOSOL MD', 'Engrase');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOZYM CL', 'Rindente');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOSLIP P', 'Deslizante');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOZYM CN', 'Rindente');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOL RK', 'Engrase');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('PASTOSOL BCN', 'Tensoactivo');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOCRYL A–90', 'Resina');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOSYL HBD', 'Hidrofugante');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOTAN OM', 'Curtición');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOSIST D', 'Hidrofugante');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOCRYL A-30', 'Resina');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOCRYL K-U-27', 'Resina');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOCRYL A-32', 'Resina');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOFIN CERA D-80', 'Cera');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOWET PH', 'Remojo');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPON PEM', 'Engrase');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOZYM CB', 'Rindente');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOCRYL A-35', 'Resina');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOFIN CERA A', 'Cera');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOCRYL K-U-327', 'Resina');
INSERT INTO productos (identificador_producto, tipo_producto) VALUES ('TRUPOZYM CH', 'Rindente');
